insert into region(name) values ('Durban');
insert into region(name) values ('Cape Town');
insert into region(name) values ('Gauteng');

insert into route(name, region_id, cost) values('Cape Town - Bellville', (select id from region where name = 'Cape Town'), 14.50);
insert into route(name, region_id, cost) values('Cape Town - Gugulethu', (select id from region where name = 'Cape Town'), 12.00);
insert into route(name, region_id, cost) values('Cape Town - Langa', (select id from region where name = 'Cape Town'), 8.00);
insert into route(name, region_id, cost) values('Sandton - Randburg', (select id from region where name = 'Gauteng'), 8.50);
insert into route(name, region_id, cost) values('Alexandra - Sandton', (select id from region where name = 'Gauteng'), 8.50);
insert into route(name, region_id, cost) values('Sandton - Midrand', (select id from region where name = 'Gauteng'), 11.00);
insert into route(name, region_id, cost) values('Umlazi - Durban Central', (select id from region where name = 'Durban'), 14.00);
insert into route(name, region_id, cost) values('Durban Central - Umbilo', (select id from region where name = 'Durban'), 17.00);
insert into route(name, region_id, cost) values('Durban Central - Umhlanga Rocks', (select id from region where name = 'Durban'), 7.00);

insert into taxi(reg_number, region_id) values('CA 934 672', (select id from region where name = 'Cape Town'));
insert into taxi(reg_number, region_id) values('CAA 204 852', (select id from region where name = 'Cape Town'));
insert into taxi(reg_number, region_id) values('CA 359 249', (select id from region where name = 'Cape Town'));
insert into taxi(reg_number, region_id) values('VS34SF GP', (select id from region where name = 'Gauteng'));
insert into taxi(reg_number, region_id) values('SL21BE GP', (select id from region where name = 'Gauteng'));
insert into taxi(reg_number, region_id) values('XP38DY GP', (select id from region where name = 'Gauteng'));
insert into taxi(reg_number, region_id) values('ND 284 983', (select id from region where name = 'Durban'));
insert into taxi(reg_number, region_id) values('ND 294 824', (select id from region where name = 'Durban'));
insert into taxi(reg_number, region_id) values('ND 233 034', (select id from region where name = 'Durban'));

insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 294 824'),	(select id from route where name = 'Umlazi - Durban Central'),	'2021-11-22 01:45:13');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 294 824'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-23 22:12:04');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 233 034'),	(select id from route where name = 'Umlazi - Durban Central'),	'2021-11-22 21:02:30');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 233 034'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-22 13:51:54');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 294 824'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-22 07:56:52');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 233 034'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-22 05:03:37');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 294 824'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-22 09:20:00');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 233 034'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-23 17:36:07');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 284 983'),	(select id from route where name = 'Durban Central - Umhlanga Rocks'),	'2021-11-23 22:53:31');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 294 824'),	(select id from route where name = 'Umlazi - Durban Central'),	'2021-11-23 11:29:46');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 284 983'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-22 22:31:38');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 294 824'),	(select id from route where name = 'Durban Central - Umhlanga Rocks'),	'2021-11-22 20:50:09');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 233 034'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-23 23:31:21');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 294 824'),	(select id from route where name = 'Durban Central - Umhlanga Rocks'),	'2021-11-23 01:11:27');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 233 034'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-22 04:35:23');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 294 824'),	(select id from route where name = 'Durban Central - Umhlanga Rocks'),	'2021-11-22 10:02:36');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 284 983'),	(select id from route where name = 'Umlazi - Durban Central'),	'2021-11-22 04:32:01');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 284 983'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-23 01:01:23');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 284 983'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-22 11:54:32');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 233 034'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-23 03:48:37');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 233 034'),	(select id from route where name = 'Durban Central - Umhlanga Rocks'),	'2021-11-23 19:42:48');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 284 983'),	(select id from route where name = 'Umlazi - Durban Central'),	'2021-11-23 23:20:34');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 233 034'),	(select id from route where name = 'Durban Central - Umbilo'),	'2021-11-22 14:51:34');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 284 983'),	(select id from route where name = 'Durban Central - Umhlanga Rocks'),	'2021-11-22 09:59:17');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'ND 294 824'),	(select id from route where name = 'Durban Central - Umhlanga Rocks'),	'2021-11-22 16:19:07');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 934 672'),	(select id from route where name = 'Cape Town - Bellville'),	'2021-11-22 12:40:54');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 934 672'),	(select id from route where name = 'Cape Town - Bellville'),	'2021-11-23 16:29:43');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 934 672'),	(select id from route where name = 'Cape Town - Gugulethu'),	'2021-11-22 08:54:01');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 359 249'),	(select id from route where name = 'Cape Town - Gugulethu'),	'2021-11-23 08:06:16');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 934 672'),	(select id from route where name = 'Cape Town - Gugulethu'),	'2021-11-23 05:46:24');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 934 672'),	(select id from route where name = 'Cape Town - Langa'),	'2021-11-22 05:39:42');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 359 249'),	(select id from route where name = 'Cape Town - Bellville'),	'2021-11-22 13:09:12');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 359 249'),	(select id from route where name = 'Cape Town - Gugulethu'),	'2021-11-23 17:29:44');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 934 672'),	(select id from route where name = 'Cape Town - Langa'),	'2021-11-23 03:23:54');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 359 249'),	(select id from route where name = 'Cape Town - Bellville'),	'2021-11-23 03:15:55');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 359 249'),	(select id from route where name = 'Cape Town - Langa'),	'2021-11-23 13:03:42');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CA 934 672'),	(select id from route where name = 'Cape Town - Langa'),	'2021-11-23 06:53:38');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CAA 204 852'),	(select id from route where name = 	'Cape Town - Bellville'),	'2021-11-23 08:12:03');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CAA 204 852'),	(select id from route where name = 	'Cape Town - Gugulethu'),	'2021-11-22 10:54:42');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CAA 204 852'),	(select id from route where name = 	'Cape Town - Bellville'),	'2021-11-23 04:58:56');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CAA 204 852'),	(select id from route where name = 	'Cape Town - Gugulethu'),	'2021-11-23 08:42:30');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'CAA 204 852'),	(select id from route where name = 	'Cape Town - Bellville'),	'2021-11-23 17:12:00');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'XP38DY GP'),	(select id from route where name = 	'Alexandra - Sandton'),'2021-11-23 04:40:11');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'XP38DY GP'),	(select id from route where name = 	'Sandton - Midrand'),'2021-11-23 00:32:15');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'VS34SF GP'),	(select id from route where name = 	'Alexandra - Sandton'),'2021-11-22 13:00:23');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'SL21BE GP'),	(select id from route where name = 	'Sandton - Midrand'),'2021-11-22 11:40:49');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'VS34SF GP'),	(select id from route where name = 	'Sandton - Midrand'),'2021-11-22 14:19:29');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'SL21BE GP'),	(select id from route where name = 	'Sandton - Randburg'),'2021-11-22 22:53:30');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'XP38DY GP'),	(select id from route where name = 	'Sandton - Randburg'),'2021-11-22 06:59:23');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'VS34SF GP'),	(select id from route where name = 	'Alexandra - Sandton'),'2021-11-23 08:46:41');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'SL21BE GP'),	(select id from route where name = 	'Sandton - Midrand'),'2021-11-22 06:39:24');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'SL21BE GP'),	(select id from route where name = 	'Alexandra - Sandton'),'2021-11-23 18:09:36');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'XP38DY GP'),	(select id from route where name = 	'Sandton - Randburg'),'2021-11-22 05:37:15');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'SL21BE GP'),	(select id from route where name = 	'Sandton - Randburg'),'2021-11-22 08:09:49');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'VS34SF GP'),	(select id from route where name = 	'Alexandra - Sandton'),'2021-11-23 21:12:57');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'SL21BE GP'),	(select id from route where name = 	'Sandton - Randburg'),'2021-11-22 20:08:07');
insert into trip(taxi_id, route_id, date_time) values((select id from taxi where reg_number = 'SL21BE GP'),	(select id from route where name = 	'Sandton - Randburg'),'2021-11-22 22:16:02');
